

spring:
  cloud:
    kubernetes:
      enabled: false
      discovery:
        enabled: false
  autoconfigure:
    exclude:
      # Disable Kubernetes autoconfigurations
      - org.springframework.cloud.kubernetes.KubernetesAutoConfiguration
      - org.springframework.cloud.kubernetes.discovery.KubernetesCatalogWatchAutoConfiguration
      - org.springframework.cloud.kubernetes.discovery.reactive.KubernetesReactiveDiscoveryClientAutoConfiguration
      - org.springframework.cloud.kubernetes.discovery.KubernetesDiscoveryClientAutoConfiguration

feign:
  hystrix:
    enabled: true

# See https://github.com/Netflix/Hystrix/wiki/Configuration
hystrix:
  command:
    default:
      execution:
        timeout:
          enable: true
        isolation:
          strategy: SEMAPHORE
          # See https://github.com/spring-cloud/spring-cloud-netflix/issues/1330
          thread:
            timeoutInMilliseconds: 15000
        circuitBreaker:
          requestVolumeThreshold: 200
          leepWindowInMilliseconds: 5000
          errorThresholdPercentage: 50
  shareSecurityContext: true
  threadpool:
    default:
      coreSize: 200
      maxQueueSize: 200
      queueSizeRejectionThreshold: 160

logging:
  level:
    org:
      apereo:
        cas:
          web: INFO
          authentication: INFO
      ldaptive: INFO